CREATE TABLE IF NOT EXISTS withdrawals (
  id SERIAL PRIMARY KEY,
  time_deposit_id INTEGER NOT NULL REFERENCES time_deposits(id) ON DELETE CASCADE,
  amount NUMERIC(20, 2) NOT NULL,
  date DATE NOT NULL
);
